/**
 * Seed Knowledge Base Properties
 * Maps dummy listings from the Mumbai & Thane Knowledge File to CRM schema
 */

import { Property, Tower, Unit, ProjectStatus, BuildingStatus, UnitStatus, UnitType } from '@/types/property';

export const knowledgeProperties: any[] = [
    {
        id: 'prop-kb-001',
        name: 'Seaview Serenity',
        code: 'BND-WEST-01',
        description: 'Sea-facing premium residence in Bandra West, near Pali Hill.',
        location: {
            city: 'Mumbai',
            locality: 'Bandra West',
            fullAddress: 'Sea View Road, Bandra West, Mumbai',
            pincode: '400050',
        },
        status: ProjectStatus.ACTIVE,
        projectType: 'RESIDENTIAL',
        developerName: 'Citizen Premier',
        totalTowers: 1,
        totalUnits: 20,
        availableUnits: 5,
        bookedUnits: 15,
        amenities: ['Sea View', 'Parking', 'Ready to Move'],
        highlights: ['8th Floor', 'Premium Neighborhood'],
        expectedCompletion: '2024-01-01T00:00:00Z',
        reraId: 'P51800099901',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'prop-kb-002',
        name: 'Urban Nest',
        code: 'AND-WEST-02',
        description: 'Modern 1 BHK in Gated Society, Andheri West.',
        location: {
            city: 'Mumbai',
            locality: 'Andheri West',
            fullAddress: 'Link Road, Andheri West, Mumbai',
            pincode: '400053',
        },
        status: ProjectStatus.ACTIVE,
        projectType: 'RESIDENTIAL',
        developerName: 'Citizen Urban',
        totalTowers: 1,
        totalUnits: 50,
        availableUnits: 12,
        bookedUnits: 38,
        amenities: ['Gym', 'Close to Metro', 'Gated Society'],
        highlights: ['High Rental Yield', 'Prime Location'],
        expectedCompletion: '2023-12-01T00:00:00Z',
        reraId: 'P51800099902',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'prop-kb-003',
        name: 'Powai Park Towers',
        code: 'POWAI-03',
        description: 'Luxury 3 BHK Lake View apartment in Powai.',
        location: {
            city: 'Mumbai',
            locality: 'Powai',
            fullAddress: 'Central Avenue, Powai, Mumbai',
            pincode: '400076',
        },
        status: ProjectStatus.UNDER_CONSTRUCTION,
        projectType: 'RESIDENTIAL',
        developerName: 'Citizen Heights',
        totalTowers: 2,
        totalUnits: 100,
        availableUnits: 40,
        bookedUnits: 60,
        amenities: ['Clubhouse', 'Swimming Pool', 'Lake View'],
        highlights: ['New Launch', 'Possession 2026'],
        expectedCompletion: '2026-06-30T00:00:00Z',
        reraId: 'P51800099903',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'prop-kb-004',
        name: 'Family Haven',
        code: 'THN-MAJI-04',
        description: 'Ideal family 2 BHK in Majiwada, Thane West.',
        location: {
            city: 'Thane',
            locality: 'Majiwada',
            fullAddress: 'Majiwada Naka, Thane West',
            pincode: '400601',
        },
        status: ProjectStatus.ACTIVE,
        projectType: 'RESIDENTIAL',
        developerName: 'Citizen Thane',
        totalTowers: 1,
        totalUnits: 40,
        availableUnits: 10,
        bookedUnits: 30,
        amenities: ['School nearby', 'Community Hall', 'Parking'],
        highlights: ['5 min to School', 'Family Friendly'],
        expectedCompletion: '2024-03-01T00:00:00Z',
        reraId: 'P51700099904',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'prop-kb-005',
        name: 'Ghodbunder Greens',
        code: 'THN-GHOD-05',
        description: 'Sustainable 2 BHK near Ghodbunder Road highway.',
        location: {
            city: 'Thane',
            locality: 'Ghodbunder Road',
            fullAddress: 'Kolshet, Thane West',
            pincode: '400607',
        },
        status: ProjectStatus.UNDER_CONSTRUCTION,
        projectType: 'RESIDENTIAL',
        developerName: 'Citizen Eco',
        totalTowers: 3,
        totalUnits: 150,
        availableUnits: 80,
        bookedUnits: 70,
        amenities: ['Upcoming Metro', 'Gated Community', 'Green Spaces'],
        highlights: ['Possession 2025', 'Metro Connectivity'],
        expectedCompletion: '2025-12-31T00:00:00Z',
        reraId: 'P51700099905',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
    // ... Simplified to 5 properties for the seed script but representative
];

export const knowledgeTowers: any[] = [
    { id: 'tower-kb-001', propertyId: 'prop-kb-001', name: 'Main Tower', floors: 15, status: BuildingStatus.READY, totalUnits: 20, availableUnits: 5 },
    { id: 'tower-kb-002', propertyId: 'prop-kb-002', name: 'Wing A', floors: 12, status: BuildingStatus.READY, totalUnits: 50, availableUnits: 12 },
    { id: 'tower-kb-003', propertyId: 'prop-kb-003', name: 'Tower 3B', floors: 25, status: BuildingStatus.STRUCTURE, totalUnits: 50, availableUnits: 20 },
    { id: 'tower-kb-004', propertyId: 'prop-kb-004', name: 'Tower B', floors: 10, status: BuildingStatus.READY, totalUnits: 40, availableUnits: 10 },
    { id: 'tower-kb-005', propertyId: 'prop-kb-005', name: 'Phase 1', floors: 18, status: BuildingStatus.FINISHING, totalUnits: 50, availableUnits: 25 }
];

export const knowledgeUnits: any[] = [
    {
        id: 'unit-kb-001',
        towerId: 'tower-kb-001',
        propertyId: 'prop-kb-001',
        unitNumber: '801',
        floor: 8,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 900,
        builtUpArea: 1100,
        basePrice: 24000000,
        totalPrice: 24000000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'unit-kb-002',
        towerId: 'tower-kb-002',
        propertyId: 'prop-kb-002',
        unitNumber: '402',
        floor: 4,
        type: UnitType.ONE_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 520,
        builtUpArea: 650,
        basePrice: 7800000,
        totalPrice: 7800000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'unit-kb-003',
        towerId: 'tower-kb-003',
        propertyId: 'prop-kb-003',
        unitNumber: '1503',
        floor: 15,
        type: UnitType.THREE_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 1250,
        builtUpArea: 1500,
        basePrice: 31000000,
        totalPrice: 31000000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'unit-kb-004',
        towerId: 'tower-kb-004',
        propertyId: 'prop-kb-004',
        unitNumber: '501',
        floor: 5,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 780,
        builtUpArea: 950,
        basePrice: 9500000,
        totalPrice: 9500000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'unit-kb-005',
        towerId: 'tower-kb-005',
        propertyId: 'prop-kb-005',
        unitNumber: '202',
        floor: 2,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 820,
        builtUpArea: 1000,
        basePrice: 6200000,
        totalPrice: 6200000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    // Adding a commercial unit as requested
    {
        id: 'unit-kb-006',
        towerId: 'tower-kb-002',
        propertyId: 'prop-kb-002',
        unitNumber: 'G-1',
        floor: 0,
        type: UnitType.SHOP,
        status: UnitStatus.AVAILABLE,
        carpetArea: 300,
        builtUpArea: 400,
        basePrice: 2800000,
        totalPrice: 2800000,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];
