/**
 * Seed Data for Property Management Enhancements
 * Includes demo data for documents, render requests, and more units
 */

import type { PropertyDocument, DocumentCategory } from '@/types/property';
import type { RenderRequest, Render3D, RenderType, RenderStatus } from '@/types/render';

// Additional seed documents
export const seedDocuments: PropertyDocument[] = [
    {
        id: 'doc-001',
        propertyId: 'prop-001',
        name: 'Skyline Residency Brochure',
        category: 'BROCHURE' as DocumentCategory,
        fileUrl: '/documents/skyline-brochure.pdf',
        fileName: 'skyline-brochure.pdf',
        fileSize: 2500000,
        mimeType: 'application/pdf',
        thumbnailUrl: '/documents/thumbs/skyline-brochure-thumb.jpg',
        uploadedBy: 'admin',
        uploadedAt: '2024-11-01T10:00:00Z',
    },
    {
        id: 'doc-002',
        propertyId: 'prop-001',
        name: 'Price Sheet - December 2024',
        category: 'PRICE_SHEET' as DocumentCategory,
        fileUrl: '/documents/skyline-price-sheet.pdf',
        fileName: 'price-sheet-dec-2024.pdf',
        fileSize: 850000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-12-01T09:00:00Z',
    },
    {
        id: 'doc-003',
        propertyId: 'prop-001',
        towerId: 'tower-001',
        name: 'Tower A Floor Plans',
        category: 'FLOOR_PLAN' as DocumentCategory,
        fileUrl: '/documents/tower-a-floor-plans.pdf',
        fileName: 'tower-a-floor-plans.pdf',
        fileSize: 4200000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-10-15T14:30:00Z',
    },
    {
        id: 'doc-004',
        propertyId: 'prop-001',
        name: 'RERA Certificate',
        category: 'RERA_CERTIFICATE' as DocumentCategory,
        fileUrl: '/documents/skyline-rera-certificate.pdf',
        fileName: 'rera-certificate.pdf',
        fileSize: 1200000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2023-01-20T11:00:00Z',
    },
    {
        id: 'doc-005',
        propertyId: 'prop-001',
        name: 'Master Layout Plan',
        category: 'LAYOUT' as DocumentCategory,
        fileUrl: '/documents/skyline-master-layout.pdf',
        fileName: 'master-layout.pdf',
        fileSize: 3800000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2023-02-10T16:00:00Z',
    },
    {
        id: 'doc-006',
        propertyId: 'prop-002',
        name: 'Green Valley Brochure',
        category: 'BROCHURE' as DocumentCategory,
        fileUrl: '/documents/greenvalley-brochure.pdf',
        fileName: 'greenvalley-brochure.pdf',
        fileSize: 3100000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-11-15T10:00:00Z',
    },
];

// Seed render requests
export const seedRenderRequests: RenderRequest[] = [
    {
        id: 'render-req-001',
        propertyId: 'prop-001',
        unitId: 'unit-001',
        requestedBy: 'lead-001',
        requestedByName: 'Rajesh Kumar',
        renderType: 'INTERIOR' as RenderType,
        description: 'Living room and master bedroom interior view with modern furniture',
        specifications: {
            viewAngle: 'Living room from entrance',
            timeOfDay: 'afternoon',
            weather: 'sunny',
            customRequirements: 'Show modern furniture setup with natural lighting',
        },
        status: 'READY' as RenderStatus,
        requestedAt: '2024-12-01T10:00:00Z',
        estimatedDelivery: '2024-12-04T18:00:00Z',
        assignedTo: 'designer-001',
        priority: 'HIGH',
        renders: [
            {
                id: 'render-001',
                requestId: 'render-req-001',
                name: 'Living Room Interior - Final',
                description: 'Modern living room with natural lighting',
                fileUrl: '/renders/unit-001-living-room.jpg',
                thumbnailUrl: '/renders/thumbs/unit-001-living-room-thumb.jpg',
                fileSize: 5200000,
                resolution: '3840x2160',
                format: 'jpg',
                uploadedBy: 'designer-001',
                uploadedAt: '2024-12-04T15:30:00Z',
                version: 1,
                isLatest: true,
            },
        ],
        createdAt: '2024-12-01T10:00:00Z',
        updatedAt: '2024-12-04T15:30:00Z',
    },
    {
        id: 'render-req-002',
        propertyId: 'prop-001',
        requestedBy: 'lead-002',
        requestedByName: 'Priya Sharma',
        renderType: 'EXTERIOR' as RenderType,
        description: 'Front elevation view of the entire property',
        specifications: {
            viewAngle: 'Front elevation',
            timeOfDay: 'evening',
            weather: 'sunny',
            customRequirements: 'Show landscaping and entrance gate',
        },
        status: 'IN_PROGRESS' as RenderStatus,
        requestedAt: '2024-12-03T14:00:00Z',
        estimatedDelivery: '2024-12-06T18:00:00Z',
        assignedTo: 'designer-002',
        priority: 'MEDIUM',
        renders: [],
        createdAt: '2024-12-03T14:00:00Z',
        updatedAt: '2024-12-04T09:00:00Z',
    },
    {
        id: 'render-req-003',
        propertyId: 'prop-001',
        requestedBy: 'lead-003',
        requestedByName: 'Amit Patel',
        renderType: 'AERIAL' as RenderType,
        description: 'Bird\'s eye view of the entire property complex',
        specifications: {
            viewAngle: 'Top view',
            timeOfDay: 'morning',
            weather: 'sunny',
            customRequirements: 'Show all three towers and amenities',
        },
        status: 'REQUESTED' as RenderStatus,
        requestedAt: '2024-12-04T11:00:00Z',
        priority: 'LOW',
        renders: [],
        createdAt: '2024-12-04T11:00:00Z',
        updatedAt: '2024-12-04T11:00:00Z',
    },
    {
        id: 'render-req-004',
        propertyId: 'prop-002',
        requestedBy: 'lead-004',
        requestedByName: 'Sneha Reddy',
        renderType: 'WALKTHROUGH' as RenderType,
        description: 'Virtual walkthrough of 2BHK unit',
        specifications: {
            viewAngle: 'Complete unit walkthrough',
            timeOfDay: 'afternoon',
            weather: 'sunny',
            customRequirements: '360-degree virtual tour',
        },
        status: 'REQUESTED' as RenderStatus,
        requestedAt: '2024-12-04T16:00:00Z',
        priority: 'URGENT',
        renders: [],
        createdAt: '2024-12-04T16:00:00Z',
        updatedAt: '2024-12-04T16:00:00Z',
    },
];

// Additional units for better demo
export const additionalSeedUnits = [
    {
        id: 'unit-007',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-101',
        floor: 1,
        type: 'TWO_BHK',
        status: 'AVAILABLE',
        carpetArea: 900,
        builtUpArea: 1250,
        facing: 'East',
        basePrice: 45000000,
        floorRise: 100000,
        plcCharges: 500000,
        totalPrice: 46150000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-008',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-102',
        floor: 1,
        type: 'THREE_BHK',
        status: 'NEGOTIATION',
        carpetArea: 1250,
        builtUpArea: 1700,
        facing: 'West',
        basePrice: 62000000,
        floorRise: 100000,
        plcCharges: 800000,
        totalPrice: 63100000,
        specifications: {
            bedrooms: 3,
            bathrooms: 3,
            balconies: 2,
            parkingSlots: 2,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-009',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-201',
        floor: 2,
        type: 'TWO_BHK',
        status: 'RESERVED',
        carpetArea: 900,
        builtUpArea: 1250,
        facing: 'North',
        basePrice: 45000000,
        floorRise: 200000,
        plcCharges: 500000,
        totalPrice: 46350000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        reservation: {
            id: 'res-002',
            unitId: 'unit-009',
            leadId: 'lead-005',
            reservedBy: 'Vikram Singh',
            reservedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
            canExtend: true,
            extendedCount: 0,
            maxExtensions: 2,
            lockedBy: 'system',
            isActive: true,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-010',
        towerId: 'tower-003',
        propertyId: 'prop-001',
        unitNumber: 'C-101',
        floor: 1,
        type: 'FOUR_BHK',
        status: 'AVAILABLE',
        carpetArea: 1800,
        builtUpArea: 2400,
        facing: 'South',
        basePrice: 90000000,
        floorRise: 100000,
        plcCharges: 1500000,
        totalPrice: 92100000,
        specifications: {
            bedrooms: 4,
            bathrooms: 4,
            balconies: 3,
            parkingSlots: 3,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
];

// Export all seed data
export const allSeedData = {
    documents: seedDocuments,
    renderRequests: seedRenderRequests,
    additionalUnits: additionalSeedUnits,
};
