/**
 * Seed Data for Property Management Enhancements
 * Includes demo data for documents, render requests, and more units
 */

import type { PropertyDocument, DocumentCategory } from '@/types/property';
import { UnitType, UnitStatus } from '@/types/property';
import type { RenderRequest, Render3D, RenderType, RenderStatus } from '@/types/render';

// Additional seed documents
export const seedDocuments: PropertyDocument[] = [
    {
        id: 'doc-001',
        propertyId: 'prop-001',
        name: 'Skyline Residency Brochure',
        category: 'BROCHURE' as DocumentCategory,
        fileUrl: '/documents/skyline-brochure.pdf',
        fileName: 'skyline-brochure.pdf',
        fileSize: 2500000,
        mimeType: 'application/pdf',
        thumbnailUrl: '/documents/thumbs/skyline-brochure-thumb.jpg',
        uploadedBy: 'admin',
        uploadedAt: '2024-11-01T10:00:00Z',
    },
    {
        id: 'doc-002',
        propertyId: 'prop-001',
        name: 'Price Sheet - December 2024',
        category: 'PRICE_SHEET' as DocumentCategory,
        fileUrl: '/documents/skyline-price-sheet.pdf',
        fileName: 'price-sheet-dec-2024.pdf',
        fileSize: 850000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-12-01T09:00:00Z',
    },
    {
        id: 'doc-003',
        propertyId: 'prop-001',
        towerId: 'tower-001',
        name: 'Tower A Floor Plans',
        category: 'FLOOR_PLAN' as DocumentCategory,
        fileUrl: '/documents/tower-a-floor-plans.pdf',
        fileName: 'tower-a-floor-plans.pdf',
        fileSize: 4200000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-10-15T14:30:00Z',
    },
    {
        id: 'doc-004',
        propertyId: 'prop-001',
        name: 'RERA Certificate',
        category: 'RERA_CERTIFICATE' as DocumentCategory,
        fileUrl: '/documents/skyline-rera-certificate.pdf',
        fileName: 'rera-certificate.pdf',
        fileSize: 1200000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2023-01-20T11:00:00Z',
    },
    {
        id: 'doc-005',
        propertyId: 'prop-001',
        name: 'Master Layout Plan',
        category: 'LAYOUT' as DocumentCategory,
        fileUrl: '/documents/skyline-master-layout.pdf',
        fileName: 'master-layout.pdf',
        fileSize: 3800000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2023-02-10T16:00:00Z',
    },
    {
        id: 'doc-006',
        propertyId: 'prop-002',
        name: 'Green Valley Brochure',
        category: 'BROCHURE' as DocumentCategory,
        fileUrl: '/documents/greenvalley-brochure.pdf',
        fileName: 'greenvalley-brochure.pdf',
        fileSize: 3100000,
        mimeType: 'application/pdf',
        uploadedBy: 'admin',
        uploadedAt: '2024-11-15T10:00:00Z',
    },
];

// Seed render requests
export const seedRenderRequests: RenderRequest[] = [
    {
        id: 'render-req-001',
        propertyId: 'prop-001',
        unitId: 'unit-001',
        sourceType: 'UNIT',
        propertyName: 'Skyline Residency',
        builderName: 'Skyline Builders',
        contactName: 'Rajesh Kumar',
        phone: '+91 9876543210',
        businessEmail: 'rajesh@kumar.com',
        renderTypes: ['INTERIOR' as RenderType],
        instructions: 'Living room and master bedroom interior view with modern furniture',
        userMedia: [],
        referenceMedia: [],
        status: 'COMPLETED' as RenderStatus,
        requestedAt: '2024-12-01T10:00:00Z',
        completedAt: '2024-12-04T15:30:00Z',
        renders: [
            {
                id: 'render-001',
                linkedTo: 'UNIT',
                propertyId: 'prop-001',
                unitId: 'unit-001',
                media: [
                    {
                        id: 'media-001',
                        type: 'IMAGE',
                        url: '/renders/unit-001-living-room.jpg',
                        fileName: 'unit-001-living-room.jpg',
                        fileSize: 5200000,
                        mimeType: 'image/jpeg',
                        uploadedAt: '2024-12-04T15:30:00Z'
                    }
                ],
                renderType: 'INTERIOR' as RenderType,
                uploadedAt: '2024-12-04T15:30:00Z'
            },
        ],
    },
    {
        id: 'render-req-002',
        propertyId: 'prop-001',
        sourceType: 'PROPERTY',
        propertyName: 'Skyline Residency',
        builderName: 'Skyline Builders',
        contactName: 'Priya Sharma',
        phone: '+91 9123456789',
        businessEmail: 'priya@sharma.com',
        renderTypes: ['EXTERIOR' as RenderType],
        instructions: 'Front elevation view of the entire property',
        userMedia: [],
        referenceMedia: [],
        status: 'IN_PROGRESS' as RenderStatus,
        requestedAt: '2024-12-03T14:00:00Z',
        renders: [],
    },
    {
        id: 'render-req-003',
        propertyId: 'prop-001',
        sourceType: 'PROPERTY',
        propertyName: 'Skyline Residency',
        builderName: 'Skyline Builders',
        contactName: 'Amit Patel',
        phone: '+91 9988776655',
        businessEmail: 'amit@patel.com',
        renderTypes: ['EXTERIOR' as RenderType],
        instructions: 'Bird\'s eye view of the entire property complex',
        userMedia: [],
        referenceMedia: [],
        status: 'PENDING' as RenderStatus,
        requestedAt: '2024-12-04T11:00:00Z',
        renders: [],
    }
];

// Additional units for better demo
export const additionalSeedUnits = [
    {
        id: 'unit-007',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-101',
        floor: 1,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 900,
        builtUpArea: 1250,
        facing: 'East',
        basePrice: 45000000,
        floorRise: 100000,
        plcCharges: 500000,
        totalPrice: 46150000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-008',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-102',
        floor: 1,
        type: UnitType.THREE_BHK,
        status: UnitStatus.NEGOTIATION,
        carpetArea: 1250,
        builtUpArea: 1700,
        facing: 'West',
        basePrice: 62000000,
        floorRise: 100000,
        plcCharges: 800000,
        totalPrice: 63100000,
        specifications: {
            bedrooms: 3,
            bathrooms: 3,
            balconies: 2,
            parkingSlots: 2,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-009',
        towerId: 'tower-002',
        propertyId: 'prop-001',
        unitNumber: 'B-201',
        floor: 2,
        type: UnitType.TWO_BHK,
        status: UnitStatus.RESERVED,
        carpetArea: 900,
        builtUpArea: 1250,
        facing: 'North',
        basePrice: 45000000,
        floorRise: 200000,
        plcCharges: 500000,
        totalPrice: 46350000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        reservation: {
            id: 'res-002',
            unitId: 'unit-009',
            leadId: 'lead-005',
            reservedBy: 'Vikram Singh',
            reservedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
            canExtend: true,
            extendedCount: 0,
            maxExtensions: 2,
            lockedBy: 'system' as 'system',
            isActive: true,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-010',
        towerId: 'tower-003',
        propertyId: 'prop-001',
        unitNumber: 'C-101',
        floor: 1,
        type: UnitType.FOUR_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 1800,
        builtUpArea: 2400,
        facing: 'South',
        basePrice: 90000000,
        floorRise: 100000,
        plcCharges: 1500000,
        totalPrice: 92100000,
        specifications: {
            bedrooms: 4,
            bathrooms: 4,
            balconies: 3,
            parkingSlots: 3,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
];

// Export all seed data
export const allSeedData = {
    documents: seedDocuments,
    renderRequests: seedRenderRequests,
    additionalUnits: additionalSeedUnits,
};
