/**
 * Seed Property Management Data
 * Converts mock data from Property_Management_Os to CRM format
 */

import type { Property, Tower, Unit, Amenity } from '@/types/property';
import { UnitType, UnitStatus, ProjectStatus, BuildingStatus } from '@/types/property';

export const seedProperties: Property[] = [
    {
        id: 'prop-001',
        code: 'SKY-001',
        projectType: 'RESIDENTIAL',
        isActive: true,
        name: 'Skyline Residency',
        description: 'Premium residential project in the heart of Andheri West with world-class amenities',
        location: {
            city: 'Mumbai',
            locality: 'Andheri West',
            fullAddress: 'Plot No. 45, S.V. Road',
            pincode: '400058',
            latitude: 19.1334,
            longitude: 72.8397,
        },
        status: ProjectStatus.ACTIVE,
        thumbnailUrl: '/images/properties/skyline-thumb.jpg',
        primaryImageUrl: '/images/properties/skyline-banner.jpg',
        totalTowers: 3,
        totalUnits: 120,
        availableUnits: 45,
        bookedUnits: 65,
        amenities: [
            { id: 'am-001', name: 'Swimming Pool', icon: 'Waves', category: 'Recreation' },
            { id: 'am-002', name: 'Gymnasium', icon: 'Dumbbell', category: 'Fitness' },
            { id: 'am-003', name: 'Clubhouse', icon: 'Home', category: 'Social' },
            { id: 'am-004', name: 'Kids Play Area', icon: 'Baby', category: 'Recreation' },
            { id: 'am-005', name: '24/7 Security', icon: 'Shield', category: 'Security' },
            { id: 'am-006', name: 'Power Backup', icon: 'Zap', category: 'Utilities' },
            { id: 'am-007', name: 'Landscaped Gardens', icon: 'Trees', category: 'Recreation' },
            { id: 'am-008', name: 'Jogging Track', icon: 'Activity', category: 'Fitness' },
        ],
        highlights: [
            'RERA approved premium project',
            'Located in prime Andheri West',
            '5 minutes from Metro Station',
            'Top-rated schools nearby',
            'Shopping malls within 1km',
            '24/7 Security with CCTV',
        ],
        launchDate: '2023-01-15T00:00:00Z',
        expectedCompletion: '2025-12-31T00:00:00Z',
        reraId: 'P51800012345',
        developerName: 'Skyline Developers Pvt Ltd',
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'prop-002',
        code: 'GVH-002',
        projectType: 'RESIDENTIAL',
        isActive: true,
        name: 'Green Valley Homes',
        description: 'Eco-friendly residential project with sustainable living features',
        location: {
            city: 'Pune',
            locality: 'Hinjewadi',
            fullAddress: 'Survey No. 123, Hinjewadi Phase 2',
            pincode: '411057',
            latitude: 18.5912,
            longitude: 73.7389,
        },
        status: ProjectStatus.UNDER_CONSTRUCTION,
        thumbnailUrl: '/images/properties/greenvalley-thumb.jpg',
        totalTowers: 4,
        totalUnits: 180,
        availableUnits: 95,
        bookedUnits: 70,
        amenities: [
            { id: 'am-009', name: 'Organic Garden', icon: 'Leaf', category: 'Eco' },
            { id: 'am-010', name: 'Jogging Track', icon: 'Activity', category: 'Fitness' },
            { id: 'am-011', name: 'Yoga Center', icon: 'Heart', category: 'Wellness' },
            { id: 'am-012', name: 'Solar Panels', icon: 'Sun', category: 'Eco' },
            { id: 'am-013', name: 'Rainwater Harvesting', icon: 'Droplet', category: 'Eco' },
            { id: 'am-014', name: 'EV Charging', icon: 'Zap', category: 'Utilities' },
        ],
        highlights: [
            'Eco-friendly green building',
            'Solar power generation',
            'Organic waste management',
            'Near IT parks and tech companies',
            'Excellent connectivity',
        ],
        launchDate: '2024-03-01T00:00:00Z',
        expectedCompletion: '2026-06-30T00:00:00Z',
        reraId: 'P52100045678',
        developerName: 'Green Valley Constructions',
        createdAt: '2024-03-01T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'prop-003',
        code: 'USQ-003',
        projectType: 'MIXED_USE',
        isActive: true,
        name: 'Urban Square',
        description: 'Mixed-use commercial development with retail and office spaces',
        location: {
            city: 'Bangalore',
            locality: 'Whitefield',
            fullAddress: 'EPIP Zone, Whitefield',
            pincode: '560066',
            latitude: 12.9698,
            longitude: 77.7499,
        },
        status: ProjectStatus.ACTIVE,
        totalTowers: 2,
        totalUnits: 85,
        availableUnits: 30,
        bookedUnits: 50,
        amenities: [
            { id: 'am-015', name: 'Retail Space', icon: 'ShoppingBag', category: 'Commercial' },
            { id: 'am-016', name: 'Food Court', icon: 'UtensilsCrossed', category: 'Dining' },
            { id: 'am-017', name: 'Office Spaces', icon: 'Briefcase', category: 'Commercial' },
            { id: 'am-018', name: 'Parking', icon: 'Car', category: 'Utilities' },
            { id: 'am-019', name: 'Elevators', icon: 'ArrowUpDown', category: 'Utilities' },
            { id: 'am-020', name: 'Conference Rooms', icon: 'Users', category: 'Business' },
        ],
        highlights: [
            'Mixed-use development',
            'Direct Metro connectivity',
            'Tech park nearby',
            'Premium retail brands',
            'High footfall area',
        ],
        launchDate: '2022-06-01T00:00:00Z',
        expectedCompletion: '2024-12-31T00:00:00Z',
        reraId: 'PRM/KA/RERA/1251/309/PR/171003/001932',
        developerName: 'Urban Spaces Ltd',
        createdAt: '2022-06-01T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
];

export const seedTowers: Tower[] = [
    {
        id: 'tower-001',
        propertyId: 'prop-001',
        name: 'Tower A',
        totalFloors: 20,
        totalUnits: 40,
        availableUnits: 15,
        status: BuildingStatus.READY,
        specifications: {
            height: '60m',
            structure: 'RCC',
            amenities: ['Lift', 'Fire Safety', 'Water Supply'],
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'tower-002',
        propertyId: 'prop-001',
        name: 'Tower B',
        totalFloors: 20,
        totalUnits: 40,
        availableUnits: 18,
        status: BuildingStatus.READY,
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'tower-003',
        propertyId: 'prop-001',
        name: 'Tower C',
        totalFloors: 20,
        totalUnits: 40,
        availableUnits: 12,
        status: BuildingStatus.FINISHING,
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'tower-004',
        propertyId: 'prop-002',
        name: 'Block A',
        totalFloors: 15,
        totalUnits: 45,
        availableUnits: 25,
        status: BuildingStatus.STRUCTURE,
        createdAt: '2024-03-01T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'tower-005',
        propertyId: 'prop-002',
        name: 'Block B',
        totalFloors: 15,
        totalUnits: 45,
        availableUnits: 22,
        status: BuildingStatus.STRUCTURE,
        createdAt: '2024-03-01T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
];

export const seedUnits: Unit[] = [
    {
        id: 'unit-001',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-101',
        floor: 1,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 850,
        builtUpArea: 1200,
        facing: 'North',
        basePrice: 42000000,
        floorRise: 100000,
        plcCharges: 500000,
        totalPrice: 43150000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-002',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-102',
        floor: 1,
        type: UnitType.THREE_BHK,
        status: UnitStatus.RESERVED,
        carpetArea: 1200,
        builtUpArea: 1650,
        facing: 'East',
        basePrice: 60000000,
        floorRise: 100000,
        plcCharges: 750000,
        totalPrice: 61050000,
        specifications: {
            bedrooms: 3,
            bathrooms: 3,
            balconies: 2,
            parkingSlots: 2,
        },
        reservation: {
            id: 'res-001',
            unitId: 'unit-002',
            leadId: 'lead-001',
            reservedBy: 'Rajesh Kumar',
            reservedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
            expiresAt: new Date(Date.now() + 47 * 60 * 60 * 1000).toISOString(),
            canExtend: true,
            extendedCount: 0,
            maxExtensions: 2,
            lockedBy: 'system',
            isActive: true,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-003',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-201',
        floor: 2,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 850,
        builtUpArea: 1200,
        facing: 'South',
        basePrice: 42000000,
        floorRise: 200000,
        plcCharges: 500000,
        totalPrice: 43350000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-004',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-202',
        floor: 2,
        type: UnitType.THREE_BHK,
        status: UnitStatus.BOOKED,
        carpetArea: 1200,
        builtUpArea: 1650,
        facing: 'West',
        basePrice: 60000000,
        floorRise: 200000,
        plcCharges: 750000,
        totalPrice: 61150000,
        specifications: {
            bedrooms: 3,
            bathrooms: 3,
            balconies: 2,
            parkingSlots: 2,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-005',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-301',
        floor: 3,
        type: UnitType.TWO_BHK,
        status: UnitStatus.AVAILABLE,
        carpetArea: 850,
        builtUpArea: 1200,
        facing: 'North',
        basePrice: 42000000,
        floorRise: 300000,
        plcCharges: 500000,
        totalPrice: 43550000,
        specifications: {
            bedrooms: 2,
            bathrooms: 2,
            balconies: 1,
            parkingSlots: 1,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
    {
        id: 'unit-006',
        towerId: 'tower-001',
        propertyId: 'prop-001',
        unitNumber: 'A-302',
        floor: 3,
        type: UnitType.THREE_BHK,
        status: UnitStatus.BLOCKED,
        carpetArea: 1200,
        builtUpArea: 1650,
        facing: 'East',
        basePrice: 60000000,
        floorRise: 300000,
        plcCharges: 750000,
        totalPrice: 61250000,
        specifications: {
            bedrooms: 3,
            bathrooms: 3,
            balconies: 2,
            parkingSlots: 2,
        },
        createdAt: '2023-01-15T00:00:00Z',
        updatedAt: '2024-12-04T00:00:00Z',
    },
];
